defaults:
  - hydra: default
  - path: default
  - type: metric_curve
  - _self_  

n_epoch: 50

epoch_len: 10000

algos:
  - drq

tasks:
  - cartpole-swingup-v0
  - cheetah-run-v0
  - ball_in_cup-catch-v0
  - walker-walk-v0
  - finger-spin-v0
