"""Practical sub-optimality: how well an agent exploits its own experience.

Implements the estimators from
    Berseth, "Is Exploration or Optimization the Problem for Deep Reinforcement
    Learning?", 2025. https://arxiv.org/abs/2508.01329

The optimality gap in `metrics.aggregate_optimality_gap` is measured against a
fixed reference such as human-normalized scores. Here the reference is instead
the best experience the agent itself generated during training: the mean of the
top-k% episodic returns, either over all episodes (*global*, D_inf) or over the
episodes in the current replay buffer / recent rollouts (*recent*, D). A large
gap between this estimate and the learned policy's return means the agent
generated better experience than it learned to reproduce, i.e. the bottleneck
is exploitation (optimization) rather than exploration.
"""

import collections
import heapq
from typing import Any, Dict, List, Optional, Union

import numpy as np


def experience_optimal_return(episode_returns, top_fraction: float = 0.05) -> float:
    """Estimates V^{pi*}(s_0) as the mean of the top `top_fraction` returns.

    Args:
      episode_returns: Episodic returns generated by the agent during training.
        Pass all episodes for the *global* estimate, or only the episodes in the
        replay buffer / recent rollouts for the *recent* estimate.
      top_fraction: Fraction k of the highest returns to average (the paper
        uses 5%). At least one return is always used.
    Returns:
      Mean of the top max(1, floor(k * N)) returns.
    """
    returns = np.asarray(episode_returns, dtype=np.float64).ravel()
    if returns.size == 0:
        raise ValueError("`episode_returns` must contain at least one return.")
    if not 0 < top_fraction <= 1:
        raise ValueError("`top_fraction` must be in (0, 1].")
    k = max(1, int(top_fraction * returns.size))
    return float(np.mean(np.sort(returns)[-k:]))


def experience_normalized_scores(scores, optimal_returns, min_returns) -> np.ndarray:
    """Normalizes scores by the experience-based optimal return.

    score = (V^{pi_theta} - V^{pi_0}) / (V^{pi*} - V^{pi_0}), so 1 means the
    policy matches the best experience it generated. Passing the result to
    `metrics.aggregate_optimality_gap` (or any other aggregate metric, with
    `library.get_interval_estimates`) gives the practical sub-optimality gap
    across runs and tasks.

    Args:
      scores: A matrix of size (`num_runs` x `num_tasks`) with the return of the
        learned policy on run `n` of task `m`.
      optimal_returns: A matrix of the same size with each run's
        experience-based optimal return (see `experience_optimal_return`).
      min_returns: Lower reference return V^{pi_0}, e.g. a random policy's
        return or the minimum return seen during training. A matrix of the same
        size, or a scalar / per-task vector that broadcasts to it.
    Returns:
      A (`num_runs` x `num_tasks`) matrix of normalized scores. Runs that never
      generated a return above `min_returns` have no measurable gap and get 1.
    """
    scores = np.asarray(scores, dtype=np.float64)
    optimal_returns = np.broadcast_to(np.asarray(optimal_returns, dtype=np.float64), scores.shape)
    min_returns = np.broadcast_to(np.asarray(min_returns, dtype=np.float64), scores.shape)
    denominator = optimal_returns - min_returns
    normalized = np.ones_like(scores)
    np.divide(scores - min_returns, denominator, out=normalized, where=denominator > 0)
    return normalized


def topk_mean_and_variance(returns, k: int) -> "tuple[float, float]":
    """Closed-form asymptotic variance of the top-k mean.

    Treats the top-k mean as a sample upper-CVaR estimator at level
    alpha = k / N (Rockafellar & Uryasev, 2000; Trindade et al., 2007):
    Var(V_k) ~= (1/k) [sigma_tail^2 + (1 - alpha)(V_k - q)^2].
    """
    returns = np.asarray(returns, dtype=np.float64).ravel()
    n = len(returns)
    k = max(1, min(k, n))
    sorted_returns = np.sort(returns)[::-1]
    top_k = sorted_returns[:k]
    v_k = float(np.mean(top_k))
    q = float(sorted_returns[k - 1])
    alpha = k / n
    sigma_tail_sq = float(np.var(top_k, ddof=1)) if k > 1 else 0.0
    var_k = (sigma_tail_sq + (1 - alpha) * (v_k - q) ** 2) / k
    return v_k, var_k


def bootstrap_topk_variance(returns, k: int, n_bootstrap: int = 200,
                            rng: Optional[np.random.Generator] = None) -> "tuple[float, float]":
    """Bootstrap estimate of Var(V_k): resample episodes with replacement and
    recompute the top-k mean each time.
    """
    rng = rng if rng is not None else np.random.default_rng()
    returns = np.asarray(returns, dtype=np.float64).ravel()
    n = len(returns)
    k = max(1, min(k, n))
    estimates = np.empty(n_bootstrap, dtype=np.float64)
    for b in range(n_bootstrap):
        sample = rng.choice(returns, size=n, replace=True)
        estimates[b] = np.mean(np.sort(sample)[::-1][:k])
    return float(estimates.mean()), float(estimates.var(ddof=1))


def compute_optimal_k(
    returns: Union[np.ndarray, List[float]],
    k_grid: Optional[List[int]] = None,
    epsilon: float = 0.10,
    method: str = "bootstrap",
    n_bootstrap: int = 200,
    rng: Optional[np.random.Generator] = None,
) -> Dict[str, Any]:
    """Selects k* = min{k : SE(V_k) / |V_k| <= epsilon}.

    The smallest (least biased toward the mean) top-k whose estimate is still
    statistically reliable to within relative precision `epsilon`.

    Args:
      returns: Episodic returns generated by the agent.
      k_grid: Candidate values of k. Defaults to 1%-50% of the episodes.
      epsilon: Target relative standard error.
      method: "bootstrap" or "closed_form" (see `topk_mean_and_variance`).
      n_bootstrap: Number of bootstrap resamples.
      rng: Optional random generator for the bootstrap.
    Returns:
      A dict with `k_star`, `alpha_star` (k_star / N), `found` (whether any k
      met `epsilon`; otherwise k_star is the largest k in the grid) and `table`
      (k -> {V_k, se, rel_se}), usable for a variance-vs-k plot.
    """
    returns = np.asarray(returns, dtype=np.float64).ravel()
    n = len(returns)
    if k_grid is None:
        fractions = [0.01, 0.02, 0.05, 0.10, 0.15, 0.20, 0.30, 0.50]
        k_grid = sorted({max(1, int(n * f)) for f in fractions if int(n * f) >= 1})
        if not k_grid:
            k_grid = [max(1, n)]

    table: Dict[int, Dict[str, float]] = {}
    k_star = k_grid[-1]
    found = False
    for k in k_grid:
        if method == "bootstrap":
            v_k, var_k = bootstrap_topk_variance(returns, k, n_bootstrap, rng)
        else:
            v_k, var_k = topk_mean_and_variance(returns, k)
        se = float(np.sqrt(max(var_k, 0.0)))
        rel_se = se / abs(v_k) if v_k != 0 else np.inf
        table[k] = {"V_k": v_k, "se": se, "rel_se": rel_se}
        if not found and rel_se <= epsilon:
            k_star = k
            found = True

    return {
        "k_star": k_star,
        "alpha_star": k_star / n if n > 0 else 0.0,
        "found": found,
        "table": table,
    }


class ExperienceGapTracker:
    """Tracks the practical sub-optimality gap online during training.

    Call `add` with the return of every finished episode and log `stats()`
    periodically. Global statistics use all episodes ever generated (D_inf);
    recent statistics use the last `buffer_size` episodes (D).

    Example:
      tracker = ExperienceGapTracker(buffer_size=1000)
      ...
      if "episode" in info:
          tracker.add(info["episode"]["r"])
      for key, value in tracker.stats().items():
          writer.add_scalar(f"charts/{key}", value, global_step)
    """

    def __init__(self, buffer_size: int, top_fraction: float = 0.05):
        self._top_fraction = top_fraction
        self._returns = collections.deque(maxlen=buffer_size)
        # Min-heap of the top returns over all episodes, sized like the paper's
        # top-k of a buffer of `buffer_size` episodes.
        self._top_global_size = max(1, int(buffer_size * top_fraction))
        self._top_global: List[float] = []
        self._max_return = -np.inf

    def add(self, episode_return: float) -> None:
        episode_return = float(episode_return)
        self._returns.append(episode_return)
        self._max_return = max(self._max_return, episode_return)
        if len(self._top_global) < self._top_global_size:
            heapq.heappush(self._top_global, episode_return)
        elif episode_return > self._top_global[0]:
            heapq.heappushpop(self._top_global, episode_return)

    def stats(self) -> Dict[str, float]:
        """Returns the global/recent optimal-return estimates and gaps.

        Keys: best_trajectory_return, avg_top_returns_global,
        avg_top_returns_local, global_optimality_gap, local_optimality_gap. The
        gaps are relative to the mean return of the recent episodes.
        """
        if not self._returns:
            return {}
        mean_return = float(np.mean(self._returns))
        top_global = float(np.mean(self._top_global))
        top_local = experience_optimal_return(list(self._returns), self._top_fraction)
        return {
            "best_trajectory_return": float(self._max_return),
            "avg_top_returns_global": top_global,
            "avg_top_returns_local": top_local,
            "global_optimality_gap": top_global - mean_return,
            "local_optimality_gap": top_local - mean_return,
        }
